### ISSUE TITLE
Credentials not found issue.

### ISSUE THREAD

**Issue by 20255-ee-066** [devlikeapro/n8n-nodes-chatwoot#2]
I have added the node to my chatwoot, I am using https://app.chatwoot.com/api/v1 this url as chatwoot api url and the access token from my profile setting, but when I save, it says not found, Please solve the issue.

**Comment by devlikepro** [comment]
try https://app.chatwoot.com (no api/v1)
![image](https://github.com/user-attachments/assets/299dfe27-00f3-4441-8360-bb724bd249d5)

**Comment by 20255-ee-066** [comment]
Done, thanks for the help.
